[features]
seeds = false
skip-lint = false

[programs.localnet]
splitter = "Gm5A2qTMjz3TMESWvBQoApGm8VuzXF1X2y7DEpJnUpda"

[programs.devnet]
splitter = "Gm5A2qTMjz3TMESWvBQoApGm8VuzXF1X2y7DEpJnUpda"

[programs.mainnet]
splitter = "Gm5A2qTMjz3TMESWvBQoApGm8VuzXF1X2y7DEpJnUpda"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "./test_keypair.json"

[scripts]
test = "npm run test:anchor"
client = "npm run client"
